# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: NodeTool@0 
  inputs:
    versionSpec: '12.x'
- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  displayName: "Unit Tests"
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\$(BuildConfiguration)\*test*.dll
      **\$(buildConfiguration)\**\*test*.dll
      !**\*TestAdapter.dll
      !**\obj\**
    searchFolder: '$(System.DefaultWorkingDirectory)'
    runOnlyImpactedTests: false
    runTestsInIsolation: true
    codeCoverageEnabled: true
    otherConsoleOptions: '/platform:x64 /Framework:.NETCoreApp,Version=v3.1 /logger:console;verbosity="normal"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
  condition: succeededOrfailed()

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '**/TEST-*.trx'
    buildPlatform: '$(buildPlatform)'
    buildConfiguration: '$(buildConfiguration)'

- task: Npm@1
  displayName: "Java Script Tests"
  inputs:
    command: 'custom'
    workingDir: 'BuildTest\ClientApp'
    customCommand: 'run test'
  condition: succeededOrfailed()

- task: PublishTestResults@2
  displayName: "Report the test results"
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TEST-*.xml'
    buildPlatform: '$(buildPlatform)'
    buildConfiguration: '$(buildConfiguration)'



