# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: UseDotNet@2
  displayName: 'Use .NET Core SDK $(dotnetSdkVersion)'
  inputs:
    packageType: 'sdk'
    version: '3.1.300'
    includePreviewVersions: true

- task: NodeTool@0 
  inputs:
    versionSpec: '12.x'


- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'D:\a\1\s\BuildTest\bin\Release\netcoreapp3.1\'
    arguments: '--no-build --configuration $(buildConfiguration)'''
  displayName: "UnitTests"

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*/MyUniteTests.csproj'
    arguments: '--no-build --configuration $(buildConfiguration)'
  displayName: "MyUnit Tests"

- task: Npm@1
  displayName: "Java Script Tests"
  inputs:
    command: 'custom'
    workingDir: 'BuildTest\ClientApp'
    customCommand: 'run test'
  condition: succeededOrfailed()


- task: PublishTestResults@2
  displayName: "Report the test results"
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '**/*.trx'
    searchFolder: '$(build.artifactStagingDirectory)'
    buildPlatform: '$(buildPlatform)'
    buildConfiguration: '$(buildConfiguration)'

- task: PublishCodeCoverageResults@1
  inputs: 
    codeCoverageTool: Cobertura # or JaCoCo
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/*coverage.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/**/coverage'